stages:
  - test

run-windows-standalone-csharp-tests:
  stage: test
  rules:
    - when: always
  tags:
    - windows
    - unity
  script:
    - sh start_tests_Windows.sh
  artifacts:
    when: always
    expire_in: 10 days
    paths:
      - /bin/Debug/netcoreapp2.1/AltUnityTesterLog.txt

run-mac-standalone-csharp-tests:
  stage: test
  rules:
    - when: always
  tags:
    - mac
    - unity
    - xcode
  script:
    - sh start_tests_Mac.sh
  artifacts:
    when: always
    expire_in: 10 days
    paths:
      - /bin/Debug/netcoreapp2.1/AltUnityTesterLog.txt
