stages:
  - test

run-windows-standalone-csharp-tests:
  stage: test
  rules:
    - when: always
  tags:
    - windows
  script:
    - sh start_tests_Windows.sh
  artifacts:
    when: always
    expire_in: 10 days
    paths:
      - AltUnityTesterLogs.log

run-mac-standalone-csharp-tests:
  stage: test
  rules:
    - when: always
  tags:
    - mac
    - unity
    - xcode
  script:
    - sh start_tests_Mac.sh
  artifacts:
    when: always
    expire_in: 10 days
    paths:
      - AltUnityTesterLogs.log
